GET http://localhost:3000/test.json

###
GET http://localhost:3000/name?name=Leon

###
GET http://localhost:3000/number?number=99

###
GET http://localhost:3000/test2/any%20words.json

###
GET http://localhost:3000/sum/5/10.json

###
GET http://localhost:3000/guesser/33.json

###
POST http://localhost:3000/test3
content-type: application/json

{
  "information": "stuff",
  "password": "stuff"
}

###
POST http://localhost:3000/guess3
content-type: application/json

{
  "number": 32
}

###
POST http://localhost:3000/login
content-type: application/json

{
  "login": "hugh",
  "password": "swordfish"
}